# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_install:
- mkdir ~/.R
- cp Makevars ~/.R
- npm install netlify-cli -g

script:
- Rscript -e 'bookdown::render_book("index.Rmd")'

after_success:
- netlify deploy -t $NETLIFY_PAT
